service: jeffpay
provider:
  name: aws
  runtime: python3.7
  region: us-west-2
  timeout: 30
  logs:
    restApi: true
  environment:
    TZ: Asia/Tokyo
    USER_WALLET_TABLE:
      Ref: UserWalletTable
    PAYMENT_HISTORY_TABLE:
      Ref: PaymentHistoryTable
    NOTIFICATION_ENDPOINT: "https://dkxmaha7zk.execute-api.us-west-2.amazonaws.com/prod/notification"
    LOCATION_ENDPOINT: "https://dkxmaha7zk.execute-api.us-west-2.amazonaws.com/prod/location"
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:*"
      Resource:
        - "*"
    - Effect: "Allow"
      Action:
        - "sqs:SendMessage"
        - "sqs:GetQueueUrl"
        - "sqs:ListQueues"
      Resource:
        - "*"

  tracing:
    apiGateway: true
    lambda: true

functions:
  CreateUser:
    handler: handler.user_create
    events:
      - http:
          path: users
          method: post
  CreateUserReceiver:
    handler: handler.user_create_receiver
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - UserCreate
              - Arn
  WalletCharge:
    handler: handler.wallet_charge
    events:
      - http:
          path: wallet/charge
          method: post
  WalletChargeReceiver:
    handler: handler.wallet_charge_receiver
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - WalletCharge
              - Arn
  WalletUse:
    handler: handler.wallet_use
    events:
      - http:
          path: wallet/use
          method: post
  WalletUseReceiver:
    handler: handler.wallet_use_receiver
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - WalletUse
              - Arn
  WalletTransfer:
    handler: handler.wallet_transfer
    events:
      - http:
          path: wallet/transfer
          method: post
  WalletTransferReceiver:
    handler: handler.wallet_transfer_receiver
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - WalletTransfer
              - Arn
  GetUserSummary:
    handler: handler.get_user_summary
    events:
      - http:
          path: users/{userId}/summary
          method: get
  GetPaymentHistory:
    handler: handler.get_payment_history
    events:
      - http:
          path: users/{userId}/history
          method: get

resources:
  Resources:
    UserWalletTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: userId
            AttributeType: S
          - AttributeName: walletId
            AttributeType: S
        KeySchema:
          - AttributeName: userId
            KeyType: HASH
        GlobalSecondaryIndexes:
          - IndexName: walletIndex
            KeySchema:
              - AttributeName: walletId
                KeyType: HASH
            Projection:
              ProjectionType: ALL
    PaymentHistoryTable:
      Type: AWS::DynamoDB::Table
      Properties:
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: walletId
            AttributeType: S
          - AttributeName: transactionId
            AttributeType: S
        KeySchema:
          - AttributeName: walletId
            KeyType: HASH
          - AttributeName: transactionId
            KeyType: RANGE
    CreateUserQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "UserCreate"
    WalletChargeQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "WalletCharge"
    WalletUseQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "WalletUse"
    WalletTransferQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "WalletTransfer"
